apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 'agent-task-executor-{{ "NAMESPACE" | env }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'agent-task-executor-{{ "NAMESPACE" | env }}'
subjects:
  - kind: ServiceAccount
    name: agent-task-executor
    namespace: '{{ "NAMESPACE" | env }}'
