// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AgentResourceListApplyConfiguration represents a declarative configuration of the AgentResourceList type for use
// with apply.
//
// AgentResourceList describes a CPU / memory / ephemeral-storage triple
// used by both Requests and Limits on AgentResources.
type AgentResourceListApplyConfiguration struct {
	// CPU is the CPU resource value (e.g. "500m").
	CPU *string `json:"cpu,omitempty"`
	// Memory is the memory resource value (e.g. "256Mi").
	Memory *string `json:"memory,omitempty"`
	// EphemeralStorage is the ephemeral-storage resource value (e.g. "1Gi").
	EphemeralStorage *string `json:"ephemeral-storage,omitempty"`
}

// AgentResourceListApplyConfiguration constructs a declarative configuration of the AgentResourceList type for use with
// apply.
func AgentResourceList() *AgentResourceListApplyConfiguration {
	return &AgentResourceListApplyConfiguration{}
}

// WithCPU sets the CPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPU field is set to the value of the last call.
func (b *AgentResourceListApplyConfiguration) WithCPU(value string) *AgentResourceListApplyConfiguration {
	b.CPU = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *AgentResourceListApplyConfiguration) WithMemory(value string) *AgentResourceListApplyConfiguration {
	b.Memory = &value
	return b
}

// WithEphemeralStorage sets the EphemeralStorage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EphemeralStorage field is set to the value of the last call.
func (b *AgentResourceListApplyConfiguration) WithEphemeralStorage(value string) *AgentResourceListApplyConfiguration {
	b.EphemeralStorage = &value
	return b
}
