// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AgentResourcesApplyConfiguration represents a declarative configuration of the AgentResources type for use
// with apply.
//
// AgentResources holds optional resource requests and limits for the agent container.
type AgentResourcesApplyConfiguration struct {
	// Requests declares the minimum resources the container needs.
	Requests *AgentResourceListApplyConfiguration `json:"requests,omitempty"`
	// Limits declares the maximum resources the container may use.
	Limits *AgentResourceListApplyConfiguration `json:"limits,omitempty"`
}

// AgentResourcesApplyConfiguration constructs a declarative configuration of the AgentResources type for use with
// apply.
func AgentResources() *AgentResourcesApplyConfiguration {
	return &AgentResourcesApplyConfiguration{}
}

// WithRequests sets the Requests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Requests field is set to the value of the last call.
func (b *AgentResourcesApplyConfiguration) WithRequests(value *AgentResourceListApplyConfiguration) *AgentResourcesApplyConfiguration {
	b.Requests = value
	return b
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *AgentResourcesApplyConfiguration) WithLimits(value *AgentResourceListApplyConfiguration) *AgentResourcesApplyConfiguration {
	b.Limits = value
	return b
}
