// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ConfigSpecApplyConfiguration represents a declarative configuration of the ConfigSpec type for use
// with apply.
//
// ConfigSpec defines the desired state of a Config.
type ConfigSpecApplyConfiguration struct {
	// Assignee is the task frontmatter assignee value that routes to this agent.
	Assignee *string `json:"assignee,omitempty"`
	// Image is the container image base name (without tag).
	Image *string `json:"image,omitempty"`
	// Heartbeat is the interval at which the agent re-spawns (e.g. "30m").
	Heartbeat *string `json:"heartbeat,omitempty"`
	// Deprecated: prefer TaskTypes (list). Stays functional indefinitely; use taskTypes for new agents.
	// TaskType is the task_type value in task frontmatter that routes to this agent.
	TaskType *string `json:"taskType,omitempty"`
	// TaskTypes is the list of task_type values in task frontmatter that route to this agent.
	// Optional when taskType is set; at least one of taskType or taskTypes must be non-empty.
	TaskTypes []string `json:"taskTypes,omitempty"`
	// Resources holds optional resource requests for the agent container.
	Resources *AgentResourcesApplyConfiguration `json:"resources,omitempty"`
	// Env holds per-agent environment variables.
	Env map[string]string `json:"env,omitempty"`
	// SecretName is the name of a K8s Secret to mount as envFrom.
	SecretName *string `json:"secretName,omitempty"`
	// VolumeClaim is the name of an existing PVC to mount.
	VolumeClaim *string `json:"volumeClaim,omitempty"`
	// VolumeMountPath is the container path where the PVC is mounted.
	VolumeMountPath *string `json:"volumeMountPath,omitempty"`
	// PriorityClassName is the Kubernetes PriorityClass name to stamp onto spawned Job PodTemplates.
	PriorityClassName *string `json:"priorityClassName,omitempty"`
	// Trigger declares the per-agent phase and status conditions under which the executor spawns a Job.
	Trigger *TriggerApplyConfiguration `json:"trigger,omitempty"`
}

// ConfigSpecApplyConfiguration constructs a declarative configuration of the ConfigSpec type for use with
// apply.
func ConfigSpec() *ConfigSpecApplyConfiguration {
	return &ConfigSpecApplyConfiguration{}
}

// WithAssignee sets the Assignee field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Assignee field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithAssignee(value string) *ConfigSpecApplyConfiguration {
	b.Assignee = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithImage(value string) *ConfigSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithHeartbeat sets the Heartbeat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Heartbeat field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithHeartbeat(value string) *ConfigSpecApplyConfiguration {
	b.Heartbeat = &value
	return b
}

// WithTaskType sets the TaskType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaskType field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithTaskType(value string) *ConfigSpecApplyConfiguration {
	b.TaskType = &value
	return b
}

// WithTaskTypes adds the given value to the TaskTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TaskTypes field.
func (b *ConfigSpecApplyConfiguration) WithTaskTypes(values ...string) *ConfigSpecApplyConfiguration {
	for i := range values {
		b.TaskTypes = append(b.TaskTypes, values[i])
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithResources(value *AgentResourcesApplyConfiguration) *ConfigSpecApplyConfiguration {
	b.Resources = value
	return b
}

// WithEnv puts the entries into the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Env field,
// overwriting an existing map entries in Env field with the same key.
func (b *ConfigSpecApplyConfiguration) WithEnv(entries map[string]string) *ConfigSpecApplyConfiguration {
	if b.Env == nil && len(entries) > 0 {
		b.Env = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Env[k] = v
	}
	return b
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithSecretName(value string) *ConfigSpecApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithVolumeClaim sets the VolumeClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeClaim field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithVolumeClaim(value string) *ConfigSpecApplyConfiguration {
	b.VolumeClaim = &value
	return b
}

// WithVolumeMountPath sets the VolumeMountPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeMountPath field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithVolumeMountPath(value string) *ConfigSpecApplyConfiguration {
	b.VolumeMountPath = &value
	return b
}

// WithPriorityClassName sets the PriorityClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityClassName field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithPriorityClassName(value string) *ConfigSpecApplyConfiguration {
	b.PriorityClassName = &value
	return b
}

// WithTrigger sets the Trigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trigger field is set to the value of the last call.
func (b *ConfigSpecApplyConfiguration) WithTrigger(value *TriggerApplyConfiguration) *ConfigSpecApplyConfiguration {
	b.Trigger = value
	return b
}
