// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	domain "github.com/bborbe/vault-cli/pkg/domain"
)

// TriggerApplyConfiguration represents a declarative configuration of the Trigger type for use
// with apply.
//
// Trigger declares the per-agent phase and status conditions under which the executor spawns a Job.
// Absent or empty lists fall back to the default allow-list (phases: planning/in_progress/ai_review; statuses: in_progress).
type TriggerApplyConfiguration struct {
	Phases   *domain.TaskPhases   `json:"phases,omitempty"`
	Statuses *domain.TaskStatuses `json:"statuses,omitempty"`
}

// TriggerApplyConfiguration constructs a declarative configuration of the Trigger type for use with
// apply.
func Trigger() *TriggerApplyConfiguration {
	return &TriggerApplyConfiguration{}
}

// WithPhases sets the Phases field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phases field is set to the value of the last call.
func (b *TriggerApplyConfiguration) WithPhases(value domain.TaskPhases) *TriggerApplyConfiguration {
	b.Phases = &value
	return b
}

// WithStatuses sets the Statuses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Statuses field is set to the value of the last call.
func (b *TriggerApplyConfiguration) WithStatuses(value domain.TaskStatuses) *TriggerApplyConfiguration {
	b.Statuses = &value
	return b
}
