// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/lib"
	"github.com/bborbe/agent/task/executor/pkg"
	"github.com/bborbe/agent/task/executor/pkg/spawner"
)

type FakeJobSpawner struct {
	IsJobActiveStub        func(context.Context, lib.TaskIdentifier) (bool, error)
	isJobActiveMutex       sync.RWMutex
	isJobActiveArgsForCall []struct {
		arg1 context.Context
		arg2 lib.TaskIdentifier
	}
	isJobActiveReturns struct {
		result1 bool
		result2 error
	}
	isJobActiveReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	SpawnJobStub        func(context.Context, lib.Task, pkg.AgentConfiguration) (string, error)
	spawnJobMutex       sync.RWMutex
	spawnJobArgsForCall []struct {
		arg1 context.Context
		arg2 lib.Task
		arg3 pkg.AgentConfiguration
	}
	spawnJobReturns struct {
		result1 string
		result2 error
	}
	spawnJobReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobSpawner) IsJobActive(arg1 context.Context, arg2 lib.TaskIdentifier) (bool, error) {
	fake.isJobActiveMutex.Lock()
	ret, specificReturn := fake.isJobActiveReturnsOnCall[len(fake.isJobActiveArgsForCall)]
	fake.isJobActiveArgsForCall = append(fake.isJobActiveArgsForCall, struct {
		arg1 context.Context
		arg2 lib.TaskIdentifier
	}{arg1, arg2})
	stub := fake.IsJobActiveStub
	fakeReturns := fake.isJobActiveReturns
	fake.recordInvocation("IsJobActive", []interface{}{arg1, arg2})
	fake.isJobActiveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJobSpawner) IsJobActiveCallCount() int {
	fake.isJobActiveMutex.RLock()
	defer fake.isJobActiveMutex.RUnlock()
	return len(fake.isJobActiveArgsForCall)
}

func (fake *FakeJobSpawner) IsJobActiveCalls(stub func(context.Context, lib.TaskIdentifier) (bool, error)) {
	fake.isJobActiveMutex.Lock()
	defer fake.isJobActiveMutex.Unlock()
	fake.IsJobActiveStub = stub
}

func (fake *FakeJobSpawner) IsJobActiveArgsForCall(i int) (context.Context, lib.TaskIdentifier) {
	fake.isJobActiveMutex.RLock()
	defer fake.isJobActiveMutex.RUnlock()
	argsForCall := fake.isJobActiveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobSpawner) IsJobActiveReturns(result1 bool, result2 error) {
	fake.isJobActiveMutex.Lock()
	defer fake.isJobActiveMutex.Unlock()
	fake.IsJobActiveStub = nil
	fake.isJobActiveReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeJobSpawner) IsJobActiveReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isJobActiveMutex.Lock()
	defer fake.isJobActiveMutex.Unlock()
	fake.IsJobActiveStub = nil
	if fake.isJobActiveReturnsOnCall == nil {
		fake.isJobActiveReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isJobActiveReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeJobSpawner) SpawnJob(arg1 context.Context, arg2 lib.Task, arg3 pkg.AgentConfiguration) (string, error) {
	fake.spawnJobMutex.Lock()
	ret, specificReturn := fake.spawnJobReturnsOnCall[len(fake.spawnJobArgsForCall)]
	fake.spawnJobArgsForCall = append(fake.spawnJobArgsForCall, struct {
		arg1 context.Context
		arg2 lib.Task
		arg3 pkg.AgentConfiguration
	}{arg1, arg2, arg3})
	stub := fake.SpawnJobStub
	fakeReturns := fake.spawnJobReturns
	fake.recordInvocation("SpawnJob", []interface{}{arg1, arg2, arg3})
	fake.spawnJobMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJobSpawner) SpawnJobCallCount() int {
	fake.spawnJobMutex.RLock()
	defer fake.spawnJobMutex.RUnlock()
	return len(fake.spawnJobArgsForCall)
}

func (fake *FakeJobSpawner) SpawnJobCalls(stub func(context.Context, lib.Task, pkg.AgentConfiguration) (string, error)) {
	fake.spawnJobMutex.Lock()
	defer fake.spawnJobMutex.Unlock()
	fake.SpawnJobStub = stub
}

func (fake *FakeJobSpawner) SpawnJobArgsForCall(i int) (context.Context, lib.Task, pkg.AgentConfiguration) {
	fake.spawnJobMutex.RLock()
	defer fake.spawnJobMutex.RUnlock()
	argsForCall := fake.spawnJobArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeJobSpawner) SpawnJobReturns(result1 string, result2 error) {
	fake.spawnJobMutex.Lock()
	defer fake.spawnJobMutex.Unlock()
	fake.SpawnJobStub = nil
	fake.spawnJobReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeJobSpawner) SpawnJobReturnsOnCall(i int, result1 string, result2 error) {
	fake.spawnJobMutex.Lock()
	defer fake.spawnJobMutex.Unlock()
	fake.SpawnJobStub = nil
	if fake.spawnJobReturnsOnCall == nil {
		fake.spawnJobReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.spawnJobReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeJobSpawner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobSpawner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ spawner.JobSpawner = new(FakeJobSpawner)
