// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/task/executor/pkg"
	v1 "k8s.io/api/batch/v1"
	v1a "k8s.io/api/core/v1"
	v1b "k8s.io/client-go/listers/core/v1"
)

type FakeJobWatcher struct {
	HandleJobStub        func(context.Context, *v1.Job)
	handleJobMutex       sync.RWMutex
	handleJobArgsForCall []struct {
		arg1 context.Context
		arg2 *v1.Job
	}
	HandlePodStub        func(context.Context, *v1a.Pod)
	handlePodMutex       sync.RWMutex
	handlePodArgsForCall []struct {
		arg1 context.Context
		arg2 *v1a.Pod
	}
	PodListerStub        func() v1b.PodLister
	podListerMutex       sync.RWMutex
	podListerArgsForCall []struct {
	}
	podListerReturns struct {
		result1 v1b.PodLister
	}
	podListerReturnsOnCall map[int]struct {
		result1 v1b.PodLister
	}
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobWatcher) HandleJob(arg1 context.Context, arg2 *v1.Job) {
	fake.handleJobMutex.Lock()
	fake.handleJobArgsForCall = append(fake.handleJobArgsForCall, struct {
		arg1 context.Context
		arg2 *v1.Job
	}{arg1, arg2})
	stub := fake.HandleJobStub
	fake.recordInvocation("HandleJob", []interface{}{arg1, arg2})
	fake.handleJobMutex.Unlock()
	if stub != nil {
		fake.HandleJobStub(arg1, arg2)
	}
}

func (fake *FakeJobWatcher) HandleJobCallCount() int {
	fake.handleJobMutex.RLock()
	defer fake.handleJobMutex.RUnlock()
	return len(fake.handleJobArgsForCall)
}

func (fake *FakeJobWatcher) HandleJobCalls(stub func(context.Context, *v1.Job)) {
	fake.handleJobMutex.Lock()
	defer fake.handleJobMutex.Unlock()
	fake.HandleJobStub = stub
}

func (fake *FakeJobWatcher) HandleJobArgsForCall(i int) (context.Context, *v1.Job) {
	fake.handleJobMutex.RLock()
	defer fake.handleJobMutex.RUnlock()
	argsForCall := fake.handleJobArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobWatcher) HandlePod(arg1 context.Context, arg2 *v1a.Pod) {
	fake.handlePodMutex.Lock()
	fake.handlePodArgsForCall = append(fake.handlePodArgsForCall, struct {
		arg1 context.Context
		arg2 *v1a.Pod
	}{arg1, arg2})
	stub := fake.HandlePodStub
	fake.recordInvocation("HandlePod", []interface{}{arg1, arg2})
	fake.handlePodMutex.Unlock()
	if stub != nil {
		fake.HandlePodStub(arg1, arg2)
	}
}

func (fake *FakeJobWatcher) HandlePodCallCount() int {
	fake.handlePodMutex.RLock()
	defer fake.handlePodMutex.RUnlock()
	return len(fake.handlePodArgsForCall)
}

func (fake *FakeJobWatcher) HandlePodCalls(stub func(context.Context, *v1a.Pod)) {
	fake.handlePodMutex.Lock()
	defer fake.handlePodMutex.Unlock()
	fake.HandlePodStub = stub
}

func (fake *FakeJobWatcher) HandlePodArgsForCall(i int) (context.Context, *v1a.Pod) {
	fake.handlePodMutex.RLock()
	defer fake.handlePodMutex.RUnlock()
	argsForCall := fake.handlePodArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobWatcher) PodLister() v1b.PodLister {
	fake.podListerMutex.Lock()
	ret, specificReturn := fake.podListerReturnsOnCall[len(fake.podListerArgsForCall)]
	fake.podListerArgsForCall = append(fake.podListerArgsForCall, struct {
	}{})
	stub := fake.PodListerStub
	fakeReturns := fake.podListerReturns
	fake.recordInvocation("PodLister", []interface{}{})
	fake.podListerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobWatcher) PodListerCallCount() int {
	fake.podListerMutex.RLock()
	defer fake.podListerMutex.RUnlock()
	return len(fake.podListerArgsForCall)
}

func (fake *FakeJobWatcher) PodListerCalls(stub func() v1b.PodLister) {
	fake.podListerMutex.Lock()
	defer fake.podListerMutex.Unlock()
	fake.PodListerStub = stub
}

func (fake *FakeJobWatcher) PodListerReturns(result1 v1b.PodLister) {
	fake.podListerMutex.Lock()
	defer fake.podListerMutex.Unlock()
	fake.PodListerStub = nil
	fake.podListerReturns = struct {
		result1 v1b.PodLister
	}{result1}
}

func (fake *FakeJobWatcher) PodListerReturnsOnCall(i int, result1 v1b.PodLister) {
	fake.podListerMutex.Lock()
	defer fake.podListerMutex.Unlock()
	fake.PodListerStub = nil
	if fake.podListerReturnsOnCall == nil {
		fake.podListerReturnsOnCall = make(map[int]struct {
			result1 v1b.PodLister
		})
	}
	fake.podListerReturnsOnCall[i] = struct {
		result1 v1b.PodLister
	}{result1}
}

func (fake *FakeJobWatcher) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobWatcher) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeJobWatcher) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeJobWatcher) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobWatcher) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobWatcher) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobWatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobWatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.JobWatcher = new(FakeJobWatcher)
