// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/task/executor/pkg"
	"github.com/bborbe/k8s"
	"k8s.io/client-go/tools/cache"
)

type FakeK8sConnector struct {
	ListenStub        func(context.Context, k8s.Namespace, cache.ResourceEventHandler) error
	listenMutex       sync.RWMutex
	listenArgsForCall []struct {
		arg1 context.Context
		arg2 k8s.Namespace
		arg3 cache.ResourceEventHandler
	}
	listenReturns struct {
		result1 error
	}
	listenReturnsOnCall map[int]struct {
		result1 error
	}
	SetupCustomResourceDefinitionStub        func(context.Context) error
	setupCustomResourceDefinitionMutex       sync.RWMutex
	setupCustomResourceDefinitionArgsForCall []struct {
		arg1 context.Context
	}
	setupCustomResourceDefinitionReturns struct {
		result1 error
	}
	setupCustomResourceDefinitionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeK8sConnector) Listen(arg1 context.Context, arg2 k8s.Namespace, arg3 cache.ResourceEventHandler) error {
	fake.listenMutex.Lock()
	ret, specificReturn := fake.listenReturnsOnCall[len(fake.listenArgsForCall)]
	fake.listenArgsForCall = append(fake.listenArgsForCall, struct {
		arg1 context.Context
		arg2 k8s.Namespace
		arg3 cache.ResourceEventHandler
	}{arg1, arg2, arg3})
	stub := fake.ListenStub
	fakeReturns := fake.listenReturns
	fake.recordInvocation("Listen", []interface{}{arg1, arg2, arg3})
	fake.listenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeK8sConnector) ListenCallCount() int {
	fake.listenMutex.RLock()
	defer fake.listenMutex.RUnlock()
	return len(fake.listenArgsForCall)
}

func (fake *FakeK8sConnector) ListenCalls(stub func(context.Context, k8s.Namespace, cache.ResourceEventHandler) error) {
	fake.listenMutex.Lock()
	defer fake.listenMutex.Unlock()
	fake.ListenStub = stub
}

func (fake *FakeK8sConnector) ListenArgsForCall(i int) (context.Context, k8s.Namespace, cache.ResourceEventHandler) {
	fake.listenMutex.RLock()
	defer fake.listenMutex.RUnlock()
	argsForCall := fake.listenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeK8sConnector) ListenReturns(result1 error) {
	fake.listenMutex.Lock()
	defer fake.listenMutex.Unlock()
	fake.ListenStub = nil
	fake.listenReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeK8sConnector) ListenReturnsOnCall(i int, result1 error) {
	fake.listenMutex.Lock()
	defer fake.listenMutex.Unlock()
	fake.ListenStub = nil
	if fake.listenReturnsOnCall == nil {
		fake.listenReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.listenReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinition(arg1 context.Context) error {
	fake.setupCustomResourceDefinitionMutex.Lock()
	ret, specificReturn := fake.setupCustomResourceDefinitionReturnsOnCall[len(fake.setupCustomResourceDefinitionArgsForCall)]
	fake.setupCustomResourceDefinitionArgsForCall = append(fake.setupCustomResourceDefinitionArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SetupCustomResourceDefinitionStub
	fakeReturns := fake.setupCustomResourceDefinitionReturns
	fake.recordInvocation("SetupCustomResourceDefinition", []interface{}{arg1})
	fake.setupCustomResourceDefinitionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionCallCount() int {
	fake.setupCustomResourceDefinitionMutex.RLock()
	defer fake.setupCustomResourceDefinitionMutex.RUnlock()
	return len(fake.setupCustomResourceDefinitionArgsForCall)
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionCalls(stub func(context.Context) error) {
	fake.setupCustomResourceDefinitionMutex.Lock()
	defer fake.setupCustomResourceDefinitionMutex.Unlock()
	fake.SetupCustomResourceDefinitionStub = stub
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionArgsForCall(i int) context.Context {
	fake.setupCustomResourceDefinitionMutex.RLock()
	defer fake.setupCustomResourceDefinitionMutex.RUnlock()
	argsForCall := fake.setupCustomResourceDefinitionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionReturns(result1 error) {
	fake.setupCustomResourceDefinitionMutex.Lock()
	defer fake.setupCustomResourceDefinitionMutex.Unlock()
	fake.SetupCustomResourceDefinitionStub = nil
	fake.setupCustomResourceDefinitionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionReturnsOnCall(i int, result1 error) {
	fake.setupCustomResourceDefinitionMutex.Lock()
	defer fake.setupCustomResourceDefinitionMutex.Unlock()
	fake.SetupCustomResourceDefinitionStub = nil
	if fake.setupCustomResourceDefinitionReturnsOnCall == nil {
		fake.setupCustomResourceDefinitionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setupCustomResourceDefinitionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeK8sConnector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeK8sConnector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.K8sConnector = new(FakeK8sConnector)
