// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	v1 "github.com/bborbe/agent-task-executor/k8s/apis/agent.benjamin-borbe.de/v1"
	"github.com/bborbe/agent-task-executor/pkg"
	"github.com/bborbe/agent-task-executor/pkg/spawner"
)

type FakeServiceReconciler struct {
	ReconcileServiceStub        func(context.Context, v1.Config, pkg.AgentConfiguration) error
	reconcileServiceMutex       sync.RWMutex
	reconcileServiceArgsForCall []struct {
		arg1 context.Context
		arg2 v1.Config
		arg3 pkg.AgentConfiguration
	}
	reconcileServiceReturns struct {
		result1 error
	}
	reconcileServiceReturnsOnCall map[int]struct {
		result1 error
	}
	UndeployServiceStub        func(context.Context, string) error
	undeployServiceMutex       sync.RWMutex
	undeployServiceArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	undeployServiceReturns struct {
		result1 error
	}
	undeployServiceReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceReconciler) ReconcileService(arg1 context.Context, arg2 v1.Config, arg3 pkg.AgentConfiguration) error {
	fake.reconcileServiceMutex.Lock()
	ret, specificReturn := fake.reconcileServiceReturnsOnCall[len(fake.reconcileServiceArgsForCall)]
	fake.reconcileServiceArgsForCall = append(fake.reconcileServiceArgsForCall, struct {
		arg1 context.Context
		arg2 v1.Config
		arg3 pkg.AgentConfiguration
	}{arg1, arg2, arg3})
	stub := fake.ReconcileServiceStub
	fakeReturns := fake.reconcileServiceReturns
	fake.recordInvocation("ReconcileService", []interface{}{arg1, arg2, arg3})
	fake.reconcileServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeServiceReconciler) ReconcileServiceCallCount() int {
	fake.reconcileServiceMutex.RLock()
	defer fake.reconcileServiceMutex.RUnlock()
	return len(fake.reconcileServiceArgsForCall)
}

func (fake *FakeServiceReconciler) ReconcileServiceCalls(stub func(context.Context, v1.Config, pkg.AgentConfiguration) error) {
	fake.reconcileServiceMutex.Lock()
	defer fake.reconcileServiceMutex.Unlock()
	fake.ReconcileServiceStub = stub
}

func (fake *FakeServiceReconciler) ReconcileServiceArgsForCall(i int) (context.Context, v1.Config, pkg.AgentConfiguration) {
	fake.reconcileServiceMutex.RLock()
	defer fake.reconcileServiceMutex.RUnlock()
	argsForCall := fake.reconcileServiceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeServiceReconciler) ReconcileServiceReturns(result1 error) {
	fake.reconcileServiceMutex.Lock()
	defer fake.reconcileServiceMutex.Unlock()
	fake.ReconcileServiceStub = nil
	fake.reconcileServiceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconciler) ReconcileServiceReturnsOnCall(i int, result1 error) {
	fake.reconcileServiceMutex.Lock()
	defer fake.reconcileServiceMutex.Unlock()
	fake.ReconcileServiceStub = nil
	if fake.reconcileServiceReturnsOnCall == nil {
		fake.reconcileServiceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.reconcileServiceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconciler) UndeployService(arg1 context.Context, arg2 string) error {
	fake.undeployServiceMutex.Lock()
	ret, specificReturn := fake.undeployServiceReturnsOnCall[len(fake.undeployServiceArgsForCall)]
	fake.undeployServiceArgsForCall = append(fake.undeployServiceArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.UndeployServiceStub
	fakeReturns := fake.undeployServiceReturns
	fake.recordInvocation("UndeployService", []interface{}{arg1, arg2})
	fake.undeployServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeServiceReconciler) UndeployServiceCallCount() int {
	fake.undeployServiceMutex.RLock()
	defer fake.undeployServiceMutex.RUnlock()
	return len(fake.undeployServiceArgsForCall)
}

func (fake *FakeServiceReconciler) UndeployServiceCalls(stub func(context.Context, string) error) {
	fake.undeployServiceMutex.Lock()
	defer fake.undeployServiceMutex.Unlock()
	fake.UndeployServiceStub = stub
}

func (fake *FakeServiceReconciler) UndeployServiceArgsForCall(i int) (context.Context, string) {
	fake.undeployServiceMutex.RLock()
	defer fake.undeployServiceMutex.RUnlock()
	argsForCall := fake.undeployServiceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeServiceReconciler) UndeployServiceReturns(result1 error) {
	fake.undeployServiceMutex.Lock()
	defer fake.undeployServiceMutex.Unlock()
	fake.UndeployServiceStub = nil
	fake.undeployServiceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconciler) UndeployServiceReturnsOnCall(i int, result1 error) {
	fake.undeployServiceMutex.Lock()
	defer fake.undeployServiceMutex.Unlock()
	fake.UndeployServiceStub = nil
	if fake.undeployServiceReturnsOnCall == nil {
		fake.undeployServiceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.undeployServiceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconciler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceReconciler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ spawner.ServiceReconciler = new(FakeServiceReconciler)
