// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent-task-executor/pkg/spawner"
)

type FakeServiceReconcileLoop struct {
	ReconcileOnceStub        func(context.Context) error
	reconcileOnceMutex       sync.RWMutex
	reconcileOnceArgsForCall []struct {
		arg1 context.Context
	}
	reconcileOnceReturns struct {
		result1 error
	}
	reconcileOnceReturnsOnCall map[int]struct {
		result1 error
	}
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceReconcileLoop) ReconcileOnce(arg1 context.Context) error {
	fake.reconcileOnceMutex.Lock()
	ret, specificReturn := fake.reconcileOnceReturnsOnCall[len(fake.reconcileOnceArgsForCall)]
	fake.reconcileOnceArgsForCall = append(fake.reconcileOnceArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ReconcileOnceStub
	fakeReturns := fake.reconcileOnceReturns
	fake.recordInvocation("ReconcileOnce", []interface{}{arg1})
	fake.reconcileOnceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeServiceReconcileLoop) ReconcileOnceCallCount() int {
	fake.reconcileOnceMutex.RLock()
	defer fake.reconcileOnceMutex.RUnlock()
	return len(fake.reconcileOnceArgsForCall)
}

func (fake *FakeServiceReconcileLoop) ReconcileOnceCalls(stub func(context.Context) error) {
	fake.reconcileOnceMutex.Lock()
	defer fake.reconcileOnceMutex.Unlock()
	fake.ReconcileOnceStub = stub
}

func (fake *FakeServiceReconcileLoop) ReconcileOnceArgsForCall(i int) context.Context {
	fake.reconcileOnceMutex.RLock()
	defer fake.reconcileOnceMutex.RUnlock()
	argsForCall := fake.reconcileOnceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeServiceReconcileLoop) ReconcileOnceReturns(result1 error) {
	fake.reconcileOnceMutex.Lock()
	defer fake.reconcileOnceMutex.Unlock()
	fake.ReconcileOnceStub = nil
	fake.reconcileOnceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconcileLoop) ReconcileOnceReturnsOnCall(i int, result1 error) {
	fake.reconcileOnceMutex.Lock()
	defer fake.reconcileOnceMutex.Unlock()
	fake.ReconcileOnceStub = nil
	if fake.reconcileOnceReturnsOnCall == nil {
		fake.reconcileOnceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.reconcileOnceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconcileLoop) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeServiceReconcileLoop) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeServiceReconcileLoop) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeServiceReconcileLoop) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeServiceReconcileLoop) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconcileLoop) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceReconcileLoop) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceReconcileLoop) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ spawner.ServiceReconcileLoop = new(FakeServiceReconcileLoop)
