// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/IBM/sarama"
	"github.com/bborbe/agent-task-executor/pkg/handler"
)

type FakeTaskEventHandler struct {
	ConsumeMessageStub        func(context.Context, *sarama.ConsumerMessage) error
	consumeMessageMutex       sync.RWMutex
	consumeMessageArgsForCall []struct {
		arg1 context.Context
		arg2 *sarama.ConsumerMessage
	}
	consumeMessageReturns struct {
		result1 error
	}
	consumeMessageReturnsOnCall map[int]struct {
		result1 error
	}
	EvalDeferredRespawnsStub        func(context.Context) error
	evalDeferredRespawnsMutex       sync.RWMutex
	evalDeferredRespawnsArgsForCall []struct {
		arg1 context.Context
	}
	evalDeferredRespawnsReturns struct {
		result1 error
	}
	evalDeferredRespawnsReturnsOnCall map[int]struct {
		result1 error
	}
	RunDeferredRespawnLoopStub        func(context.Context) error
	runDeferredRespawnLoopMutex       sync.RWMutex
	runDeferredRespawnLoopArgsForCall []struct {
		arg1 context.Context
	}
	runDeferredRespawnLoopReturns struct {
		result1 error
	}
	runDeferredRespawnLoopReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTaskEventHandler) ConsumeMessage(arg1 context.Context, arg2 *sarama.ConsumerMessage) error {
	fake.consumeMessageMutex.Lock()
	ret, specificReturn := fake.consumeMessageReturnsOnCall[len(fake.consumeMessageArgsForCall)]
	fake.consumeMessageArgsForCall = append(fake.consumeMessageArgsForCall, struct {
		arg1 context.Context
		arg2 *sarama.ConsumerMessage
	}{arg1, arg2})
	stub := fake.ConsumeMessageStub
	fakeReturns := fake.consumeMessageReturns
	fake.recordInvocation("ConsumeMessage", []interface{}{arg1, arg2})
	fake.consumeMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskEventHandler) ConsumeMessageCallCount() int {
	fake.consumeMessageMutex.RLock()
	defer fake.consumeMessageMutex.RUnlock()
	return len(fake.consumeMessageArgsForCall)
}

func (fake *FakeTaskEventHandler) ConsumeMessageCalls(stub func(context.Context, *sarama.ConsumerMessage) error) {
	fake.consumeMessageMutex.Lock()
	defer fake.consumeMessageMutex.Unlock()
	fake.ConsumeMessageStub = stub
}

func (fake *FakeTaskEventHandler) ConsumeMessageArgsForCall(i int) (context.Context, *sarama.ConsumerMessage) {
	fake.consumeMessageMutex.RLock()
	defer fake.consumeMessageMutex.RUnlock()
	argsForCall := fake.consumeMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskEventHandler) ConsumeMessageReturns(result1 error) {
	fake.consumeMessageMutex.Lock()
	defer fake.consumeMessageMutex.Unlock()
	fake.ConsumeMessageStub = nil
	fake.consumeMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskEventHandler) ConsumeMessageReturnsOnCall(i int, result1 error) {
	fake.consumeMessageMutex.Lock()
	defer fake.consumeMessageMutex.Unlock()
	fake.ConsumeMessageStub = nil
	if fake.consumeMessageReturnsOnCall == nil {
		fake.consumeMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.consumeMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskEventHandler) EvalDeferredRespawns(arg1 context.Context) error {
	fake.evalDeferredRespawnsMutex.Lock()
	ret, specificReturn := fake.evalDeferredRespawnsReturnsOnCall[len(fake.evalDeferredRespawnsArgsForCall)]
	fake.evalDeferredRespawnsArgsForCall = append(fake.evalDeferredRespawnsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.EvalDeferredRespawnsStub
	fakeReturns := fake.evalDeferredRespawnsReturns
	fake.recordInvocation("EvalDeferredRespawns", []interface{}{arg1})
	fake.evalDeferredRespawnsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskEventHandler) EvalDeferredRespawnsCallCount() int {
	fake.evalDeferredRespawnsMutex.RLock()
	defer fake.evalDeferredRespawnsMutex.RUnlock()
	return len(fake.evalDeferredRespawnsArgsForCall)
}

func (fake *FakeTaskEventHandler) EvalDeferredRespawnsCalls(stub func(context.Context) error) {
	fake.evalDeferredRespawnsMutex.Lock()
	defer fake.evalDeferredRespawnsMutex.Unlock()
	fake.EvalDeferredRespawnsStub = stub
}

func (fake *FakeTaskEventHandler) EvalDeferredRespawnsArgsForCall(i int) context.Context {
	fake.evalDeferredRespawnsMutex.RLock()
	defer fake.evalDeferredRespawnsMutex.RUnlock()
	argsForCall := fake.evalDeferredRespawnsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTaskEventHandler) EvalDeferredRespawnsReturns(result1 error) {
	fake.evalDeferredRespawnsMutex.Lock()
	defer fake.evalDeferredRespawnsMutex.Unlock()
	fake.EvalDeferredRespawnsStub = nil
	fake.evalDeferredRespawnsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskEventHandler) EvalDeferredRespawnsReturnsOnCall(i int, result1 error) {
	fake.evalDeferredRespawnsMutex.Lock()
	defer fake.evalDeferredRespawnsMutex.Unlock()
	fake.EvalDeferredRespawnsStub = nil
	if fake.evalDeferredRespawnsReturnsOnCall == nil {
		fake.evalDeferredRespawnsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.evalDeferredRespawnsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskEventHandler) RunDeferredRespawnLoop(arg1 context.Context) error {
	fake.runDeferredRespawnLoopMutex.Lock()
	ret, specificReturn := fake.runDeferredRespawnLoopReturnsOnCall[len(fake.runDeferredRespawnLoopArgsForCall)]
	fake.runDeferredRespawnLoopArgsForCall = append(fake.runDeferredRespawnLoopArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunDeferredRespawnLoopStub
	fakeReturns := fake.runDeferredRespawnLoopReturns
	fake.recordInvocation("RunDeferredRespawnLoop", []interface{}{arg1})
	fake.runDeferredRespawnLoopMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskEventHandler) RunDeferredRespawnLoopCallCount() int {
	fake.runDeferredRespawnLoopMutex.RLock()
	defer fake.runDeferredRespawnLoopMutex.RUnlock()
	return len(fake.runDeferredRespawnLoopArgsForCall)
}

func (fake *FakeTaskEventHandler) RunDeferredRespawnLoopCalls(stub func(context.Context) error) {
	fake.runDeferredRespawnLoopMutex.Lock()
	defer fake.runDeferredRespawnLoopMutex.Unlock()
	fake.RunDeferredRespawnLoopStub = stub
}

func (fake *FakeTaskEventHandler) RunDeferredRespawnLoopArgsForCall(i int) context.Context {
	fake.runDeferredRespawnLoopMutex.RLock()
	defer fake.runDeferredRespawnLoopMutex.RUnlock()
	argsForCall := fake.runDeferredRespawnLoopArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTaskEventHandler) RunDeferredRespawnLoopReturns(result1 error) {
	fake.runDeferredRespawnLoopMutex.Lock()
	defer fake.runDeferredRespawnLoopMutex.Unlock()
	fake.RunDeferredRespawnLoopStub = nil
	fake.runDeferredRespawnLoopReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskEventHandler) RunDeferredRespawnLoopReturnsOnCall(i int, result1 error) {
	fake.runDeferredRespawnLoopMutex.Lock()
	defer fake.runDeferredRespawnLoopMutex.Unlock()
	fake.RunDeferredRespawnLoopStub = nil
	if fake.runDeferredRespawnLoopReturnsOnCall == nil {
		fake.runDeferredRespawnLoopReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runDeferredRespawnLoopReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskEventHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTaskEventHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.TaskEventHandler = new(FakeTaskEventHandler)
