// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	agentbenjaminborbedev1 "github.com/bborbe/agent/task/executor/k8s/apis/agent.benjamin-borbe.de/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ConfigLister helps list Configs.
// All objects returned here must be treated as read-only.
type ConfigLister interface {
	// List lists all Configs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentbenjaminborbedev1.Config, err error)
	// Configs returns an object that can list and get Configs.
	Configs(namespace string) ConfigNamespaceLister
	ConfigListerExpansion
}

// configLister implements the ConfigLister interface.
type configLister struct {
	listers.ResourceIndexer[*agentbenjaminborbedev1.Config]
}

// NewConfigLister returns a new ConfigLister.
func NewConfigLister(indexer cache.Indexer) ConfigLister {
	return &configLister{listers.New[*agentbenjaminborbedev1.Config](indexer, agentbenjaminborbedev1.Resource("config"))}
}

// Configs returns an object that can list and get Configs.
func (s *configLister) Configs(namespace string) ConfigNamespaceLister {
	return configNamespaceLister{listers.NewNamespaced[*agentbenjaminborbedev1.Config](s.ResourceIndexer, namespace)}
}

// ConfigNamespaceLister helps list and get Configs.
// All objects returned here must be treated as read-only.
type ConfigNamespaceLister interface {
	// List lists all Configs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentbenjaminborbedev1.Config, err error)
	// Get retrieves the Config from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agentbenjaminborbedev1.Config, error)
	ConfigNamespaceListerExpansion
}

// configNamespaceLister implements the ConfigNamespaceLister
// interface.
type configNamespaceLister struct {
	listers.ResourceIndexer[*agentbenjaminborbedev1.Config]
}
