// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by lister-gen. DO NOT EDIT.

package v1

// ConfigListerExpansion allows custom methods to be added to
// ConfigLister.
type ConfigListerExpansion interface{}

// ConfigNamespaceListerExpansion allows custom methods to be added to
// ConfigNamespaceLister.
type ConfigNamespaceListerExpansion interface{}
