// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/bborbe/agent/task/executor/k8s/apis/agent.benjamin-borbe.de/v1"
	agentbenjaminborbedev1 "github.com/bborbe/agent/task/executor/k8s/client/applyconfiguration/agent.benjamin-borbe.de/v1"
	typedagentbenjaminborbedev1 "github.com/bborbe/agent/task/executor/k8s/client/clientset/versioned/typed/agent.benjamin-borbe.de/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeConfigs implements ConfigInterface
type fakeConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1.Config, *v1.ConfigList, *agentbenjaminborbedev1.ConfigApplyConfiguration]
	Fake *FakeAgentV1
}

func newFakeConfigs(fake *FakeAgentV1, namespace string) typedagentbenjaminborbedev1.ConfigInterface {
	return &fakeConfigs{
		gentype.NewFakeClientWithListAndApply[*v1.Config, *v1.ConfigList, *agentbenjaminborbedev1.ConfigApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("configs"),
			v1.SchemeGroupVersion.WithKind("Config"),
			func() *v1.Config { return &v1.Config{} },
			func() *v1.ConfigList { return &v1.ConfigList{} },
			func(dst, src *v1.ConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ConfigList) []*v1.Config { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ConfigList, items []*v1.Config) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
