// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	agentbenjaminborbedev1 "github.com/bborbe/agent/task/executor/k8s/apis/agent.benjamin-borbe.de/v1"
	scheme "github.com/bborbe/agent/task/executor/k8s/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type AgentV1Interface interface {
	RESTClient() rest.Interface
	ConfigsGetter
}

// AgentV1Client is used to interact with features provided by the agent.benjamin-borbe.de group.
type AgentV1Client struct {
	restClient rest.Interface
}

func (c *AgentV1Client) Configs(namespace string) ConfigInterface {
	return newConfigs(c, namespace)
}

// NewForConfig creates a new AgentV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*AgentV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new AgentV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*AgentV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &AgentV1Client{client}, nil
}

// NewForConfigOrDie creates a new AgentV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AgentV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AgentV1Client for the given RESTClient.
func New(c rest.Interface) *AgentV1Client {
	return &AgentV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := agentbenjaminborbedev1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AgentV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
