// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	agentbenjaminborbedev1 "github.com/bborbe/agent/task/executor/k8s/apis/agent.benjamin-borbe.de/v1"
	applyconfigurationagentbenjaminborbedev1 "github.com/bborbe/agent/task/executor/k8s/client/applyconfiguration/agent.benjamin-borbe.de/v1"
	scheme "github.com/bborbe/agent/task/executor/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ConfigsGetter has a method to return a ConfigInterface.
// A group's client should implement this interface.
type ConfigsGetter interface {
	Configs(namespace string) ConfigInterface
}

// ConfigInterface has methods to work with Config resources.
type ConfigInterface interface {
	Create(ctx context.Context, config *agentbenjaminborbedev1.Config, opts metav1.CreateOptions) (*agentbenjaminborbedev1.Config, error)
	Update(ctx context.Context, config *agentbenjaminborbedev1.Config, opts metav1.UpdateOptions) (*agentbenjaminborbedev1.Config, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*agentbenjaminborbedev1.Config, error)
	List(ctx context.Context, opts metav1.ListOptions) (*agentbenjaminborbedev1.ConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *agentbenjaminborbedev1.Config, err error)
	Apply(ctx context.Context, config *applyconfigurationagentbenjaminborbedev1.ConfigApplyConfiguration, opts metav1.ApplyOptions) (result *agentbenjaminborbedev1.Config, err error)
	ConfigExpansion
}

// configs implements ConfigInterface
type configs struct {
	*gentype.ClientWithListAndApply[*agentbenjaminborbedev1.Config, *agentbenjaminborbedev1.ConfigList, *applyconfigurationagentbenjaminborbedev1.ConfigApplyConfiguration]
}

// newConfigs returns a Configs
func newConfigs(c *AgentV1Client, namespace string) *configs {
	return &configs{
		gentype.NewClientWithListAndApply[*agentbenjaminborbedev1.Config, *agentbenjaminborbedev1.ConfigList, *applyconfigurationagentbenjaminborbedev1.ConfigApplyConfiguration](
			"configs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *agentbenjaminborbedev1.Config { return &agentbenjaminborbedev1.Config{} },
			func() *agentbenjaminborbedev1.ConfigList { return &agentbenjaminborbedev1.ConfigList{} },
		),
	}
}
